# Generated by Django 4.2.7 on 2026-02-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='whatsapp',
            field=models.CharField(help_text='WhatsApp number (e.g., 263784342632)', max_length=20),
        ),
    ]
