# Generated by Django 4.2.7 on 2026-02-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_companyinfo_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, help_text='Your physical product code (e.g., EYE-PHO-042, SKU-12345)', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='whatsapp_share_message',
            field=models.TextField(blank=True, help_text='Custom WhatsApp share message (leave blank for auto-generated)'),
        ),
    ]
