# Generated by Django 4.2.7 on 2026-02-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_product_code_product_whatsapp_share_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, help_text='Your physical product code (e.g., EYE-PHO-042, SKU-12345)', max_length=50, null=True, unique=True),
        ),
    ]
