# Generated by Django 6.0 on 2026-03-24 10:29

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_add_whatsapp_share_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
